export const PAGES_ROUTES = {
  careerDashboard: "/dashboard",
  participant: "/participant",
  compliance: "/compliance",
  policies: "/policies",
  pulseChat: "/pulse-chat",
  policyManagement: "/policy-management",
  calendar: "/calendar",
  login: "/login",
  signup: "/signup",
  verifyEmail: "/verify-email",
  createPassword: "/create-password",
  emailTemplate: "/email-template",
  accountCompletion: "/account-completion",
  loginPassword: "/login/password",
  loginCheckEmail: "/login/check-email",
  setPassword: "/set-password",
  dashboardRegistration: "/dashboard/registration",
  dashboardOnboarding: "/dashboard/onboarding",
  onboardingMediaViewer: "/dashboard/onboarding/media-viewer",
  onboardingRegistration: "/dashboard/onboarding/registration-groups",
  onboardingSummary: "/dashboard/onboarding/summary",
  dashboardForms: "/dashboard/policy-packs",
  dashboardCompliance: "/dashboard/compliance",
  dashboardFiles: "/dashboard/files",
  dashboardFeed: "/dashboard/feed",
  form: (id?: string) => `/dashboard/policy-packs/forms/${id || ""}`,
  policyDetail: (id?: string) =>
    `/dashboard/policy-packs/policy-detail/${id || ""}`,
  legislation: "/dashboard/policy-packs/legislation/",
  procedure: "/dashboard/policy-packs/procedure",
  policy: "/dashboard/policy-packs/policies",
};
